---
title: "p8105_hw2_mss2284"
author: "Maya Spaur"
date: "9/25/2019"
output: github_document
---
```{r setup}
library(tidyverse)
library(dplyr)
library(readxl)
```

##Problem 1

```{r problem 1 part 1}
trash_wheel_data = 
  read_excel("./HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = "Mr. Trash Wheel") %>%
  janitor::clean_names() %>%
  drop_na(dumpster) %>%
  mutate(
     sports_balls = round(sports_balls),
     sports_balls = as.integer(sports_balls)
  )
  
view(trash_wheel_data)


```


```{r problem 1 part 2}
precipitation_data_2017=
  read_excel("./HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = "2017 Precipitation", skip = 1, col_names = TRUE) %>%
  janitor::clean_names() %>%
  drop_na(total, month) %>%
  mutate(
  year = 2017
)

view(precipitation_data_2017)
  
precipitation_data_2018=
  read_excel("./HealthyHarborWaterWheelTotals2018-7-28.xlsx", sheet = "2018 Precipitation",  skip = 1, col_names = TRUE) %>%
  janitor::clean_names() %>%
  drop_na(total, month) %>%
  mutate(
  year = 2018
)
  
view(precipitation_data_2018)

precipitation_data = 
  full_join(precipitation_data_2017, precipitation_data_2018, by = c("month", "total", "year")) %>%
  mutate(
    month = month.name[month]
  )

view(precipitation_data)
```




